# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Saldo')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Saque',
            fields=[
                ('conta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='conta_saque', serialize=False, to='conta.Conta')),
                ('quantidade_notas', models.IntegerField()),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caixa_saque', to='conta.Caixa')),
            ],
            options={
                'verbose_name': 'Saque',
                'verbose_name_plural': 'Saques',
            },
        ),
    ]
