# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(choices=[('1', 'P$1'), ('2', 'P$2'), ('5', 'P$5'), ('10', 'P$10'), ('20', 'P$20'), ('50', 'P$50'), ('100', 'P$100')], default='1', max_length=3, verbose_name='cedula')),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
            },
        ),
    ]
