# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_caixa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='id',
        ),
        migrations.AlterField(
            model_name='caixa',
            name='cedula',
            field=models.CharField(choices=[('1', 'P$1'), ('2', 'P$2'), ('5', 'P$5'), ('10', 'P$10'), ('20', 'P$20'), ('50', 'P$50'), ('100', 'P$100')], default='1', max_length=3, primary_key=True, serialize=False, verbose_name='cedula'),
        ),
    ]
