# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_auto_20170803_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='saque',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saque',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_saque', to='conta.Conta', verbose_name='id_conta'),
        ),
    ]
